### ISSUE TITLE
Master Review

### ISSUE THREAD

**Issue by Piercel2022** [AsimKhan2019/HTML_Mobile_Exercise#20]

**Comment by MaiRizk** [comment]
1- Amazing animations for the nav icons, really like it!
2- The first introduction section looks great on the desktop version but it doesn't look the same in the mobile and tablet versions. Actually, the whole portfolio's width has an issue in the mobile and desktop version.
3- Really cool animations for the card image. 
4- The card height is not the same for all cards. Also, the column gap is different in each card, impacting the overall look of the cards section. The height and width of images are not the same as well. So I suggest fixing the card width, the image width and height, and the column gap for all cards for a better experience. 
5- Very cool animations for buttons hover. 
6- The border radius left for the contact me form is a bit too much, I suggest changing it to 100px instead of 297px

**Comment by AsimKhan2019** [comment]
@MaiRizk Thank you for the comments. Yes I do agree with the points mentioned, and I will improve them.

**Comment by ifzyy** [comment]
### Highlights

- Website is responsive
- Website looks really good
- Animation effect is also very nice

I think you've done a very good job 
keep it up👍

**Comment by Piercel2022** [comment]
Good job so far! There are some work to do in the contact form and the textarea is not so breit as in the figma design and the name and email are so big
